ver: 1.0

file:
    path: '/local/mprince/pristine_scan1/Twin_pristine_1.h5'
    output: 'outputs/ene_gpu'
    range: [0, 271, 1]
    threshold: 20 # [readout values]
    frame: [0, 2048, 0, 2048] # [pixels] 
    ext: 'h5'
    stacked: False
    h5:
        key: '/entry1/data/data'

comp:
    server: 'acc'
    use_gpu: true
    batch_size: 300
    #server: 'local'
    workers: 1
    scannumber: 1
    #functionid: 'd8461388-9442-4008-a5f1-2cfa112f6923'
    scanstart: 0

geo:
    mask: 
        path: '../masks/code-debruijn-2-8-000.npy'
        reversed: False
        bitsizes: [15, 7.5] # [mu]
        thickness: 3.73901367 # [mu]
        resolution: 0.5
        smoothness: 0 # [mu]
        alpha: 0 
        widening: 0 # [mu]
        pad: 300
        stretch: 1.0
        shift: 0.025

        focus: 
            cenx: 0.68586250435
            dist: 1.95953437436
            anglez: 43.72070312
            angley: -0.56640625
            anglex: 0.28515625
            cenz: 0.34765625

        calibrate: 
            dist: [0.01, 0.01, 0.001] # [mm] 0.619

    scanner:
        step: 1 # [mu]
        rot: [0.0045, -0.00684, -3.375e-5]
        axis: [0.70710678118, 0.70710678118, 0]

    detector: 
        shape: [2048, 2048] # [pixels]
        size: [409.6, 409.6] # [mm]
        rot: [-1.20161887, -1.21404493, -1.21852276] # [radian]
        pos: [28.828, 2.715, 512.993] # [mm]

    source: 
        offset: 0
        grid: [-0.2, -0.0, 0.001] # [mm] 0.619

algo:
    iter: 1
    pos: 
        method: 'lsqr' 
        regpar: 0
        init: 'spline'

    sig: 
        recon: True
        method: 'splines' 
        order: 5
        scale: 3
        init:
            maxsize: 128 
            avgsize: 10
            atol: 4
    ene:
        recon: True
        exact: True
        method: 'lsqr' 
        range: [1, 100, 1]