ver: 1.0

file:
    path: '/eagle/APSDataAnalysis/mrdiamond/laue_data/Indent2_twin2_3D_scan13/1'
    output: '/eagle/APSDataAnalysis/mrdiamond/twin_recon_output/recon_27/'
    pixmask: '/eagle/APSDataAnalysis/mrdiamond/laue-parallel/im_masks/0056_mask1_threshold_Twin2Indent2_2024_05_14.npy'
    range: [10, 271, 1]
    threshold: 0 # [readout values]
    frame: [0, 2048, 0, 2048] # [pixels] 
    ext: 'h5'
    stacked: False
    h5:
        key: '/entry1/data/data'


comp:
    server: 'proc'
    use_gpu: true
    batch_size: 300
    #server: 'local'
    workers: 1
    scannumber: 1
    #functionid: 'd8461388-9442-4008-a5f1-2cfa112f6923'
    scanstart: 0

geo:
    mask: 
        path: '../masks/code-debruijn-2-8-000.npy'
        reversed: False
        bitsizes: [15, 7.5] # [mu]
        thickness: 3.7 # [mu]
        resolution: 0.5
        smoothness: 0 # [mu]
        alpha: 0 
        widening: 0 # [mu]
        pad: 300
        stretch: 1.0
        shift: 0.22 # [mu] 0.21 (-70mu) + 0.01 (10pix discarded)
        focus: 
            cenx: 0.443310547
            dist: 1.60405273
            anglez: 43.3119141
            angley: -0.662109375
            anglex: -0.001953125
            cenz: 0.935546875

        calibrate: 
            dist: [0.01, 0.01, 0.001] # [mm] 0.619

    scanner:
        step: 1 # [mu]
        rot: [0.0045, -0.00684, -3.375e-5]
        axis: [0.70710678118, 0.70710678118, 0]

    detector: 
        shape: [2048, 2048] # [pixels]
        size: [409.6, 409.6] # [mm]
        rot: [-1.20161887, -1.21404493, -1.21852276] # [radian]
        pos: [28.828, 2.715, 512.993] # [mm]

    source: 
        offset: 0
        grid: [-0.1, 0.3, 0.001] # [mm] 0.619

algo:
    iter: 1
    pos: 
        method: 'lsqr' 
        regpar: 0
        init: 'spline'

    sig: 
        recon: True
        method: 'splines' 
        order: 5
        scale: 1
        init:
            maxsize: 64 
            avgsize: 10
            atol: 4
    ene:
        recon: True
        exact: True
        method: 'lsqr' 
        range: [10, 40, 1]