
ver: 1.0

file:
    path: '/local/lau_34/data/Si_Norcada_90_calib3/'
    output: 'tmp/calibrate/recon-Si_Norcada_90_calib3_maskx1800'
    range: [0, 300, 1]
    threshold: 20 # [readout values]
    frame: [0, 2048, 0, 2048] # [pixels] 
    ext: 'h5'
    stacked: True
    h5:
        key: '/entry1/data/data'

comp:
    server: 'local'
    workers: 8
    functionid: 'd8461388-9442-4008-a5f1-2cfa112f6923'

geo:
    mask: 
        path: '../masks/code-debruijn-2-8-000.npy'
        reversed: False
        bitsizes: [15, 7.5] # [mu]
        thickness: 3.7 # [mu]
        resolution: 0.5
        smoothness: 0 # [mu]
        alpha: 0 
        widening: 0 # [mu]
        pad: 300
        stretch: 1.0
        shift: 0.21 # [mu]

        focus: 
            cenx: 0.44223633
            dist: 1.60844727
            anglez: 43.84902344
            angley: -0.47070312
            anglex: 0.09179688
            cenz: 0.75195312
            
        cal: 
            id: 1
            path: 'calibrate3_maskx1800'

    scanner:
        step: 0.5 # [mu]
        rot: [0.0045, -0.00684, -3.375e-5]
        axis: [0.70710678118, 0.70710678118, 0]

    detector: 
        shape: [2048, 2048] # [pixels]
        size: [409.6, 409.6] # [mm]
        rot: [-1.20161887, -1.21404493, -1.21852276] # [radian]
        pos: [28.828, 2.715, 512.993] # [mm]

    source: 
        offset: 0
        grid: [-0.2, 0.2, 0.001] # [mm] 0.619

algo:
    iter: 1
    pos: 
        method: 'lsqr' 
        regpar: 0
        init: 'spline'

    sig: 
        recon: True
        method: 'splines' 
        order: 5
        scale: 1
        init:
            maxsize: 64 
            avgsize: 10
            atol: 4
    ene:
        recon: True
        exact: True
        method: 'lsqr' 
        range: [5, 30, 1]

