ver: 1.0

file:
    path: '/eagle/APSDataAnalysis/mprince/lau/data/63_Si_MaskZfly_1.h5'
    output: '/eagle/APSDataAnalysis/mprince/lau/dev/laue-parallel/outputs/'
    pixmask: '../recon_masks/0042_mask_calib3_maskX800_dataset42.npy'
    range: [10, 701, 1]
    threshold: 0 # [readout values]
    frame: [0, 2048, 0, 2048] # [pixels] 
    ext: 'h5'
    stacked: True
    h5:
        key: '/entry1/data/data'

comp:
    server: 'proc'
    use_gpu: true
    batch_size: 300
    #server: 'local'
    workers: 1
    scannumber: 1
    #functionid: 'd8461388-9442-4008-a5f1-2cfa112f6923'
    scanstart: 0

geo:
    mask: 
        path: '../masks/code-debruijn-2-8-000.npy'
        reversed: False
        bitsizes: [15, 7.5] # [mu]
        thickness: 4.6 # [mu]
        resolution: 0.5
        smoothness: 0 # [mu]
        alpha: 0 
        widening: 1.7 #[mu]
        pad: 150
        stretch: 1.0
        shift: 0.0

        focus:
            cenx: -0.0883125
            dist: 0.36806641
            cenz: -1.67861328
            anglex: -0.20322266
            angley: -0.28027344
            anglez: -1.01757813

        calibrate: 
            dist: [0.01, 0.01, 0.001] # [mm] 0.619

    scanner:
        step: 0.5 # [mu]
        rot: [0.0045, -0.00684, -3.375e-5]
        axis: [0.70710678118, 0.70710678118, 0]

    detector: 
        shape: [2048, 2048] # [pixels]
        size: [409.6, 409.6] # [mm]
        rot: [-1.20161887, -1.21404493, -1.21852276] # [radian]
        pos: [28.828, 2.715, 512.993] # [mm]

    source: 
        offset: 0
        grid: [-0.3, 0.3, 0.0005] # [mm] 0.619

algo:
    iter: 1
    pos: 
        method: 'lsqr' 
        regpar: 0
        init: 'spline'

    sig: 
        recon: True
        method: 'splines' 
        order: 5
        scale: 1
        init:
            maxsize: 64 
            avgsize: 10
            atol: 4
    ene:
        recon: True
        exact: True
        method: 'lsqr' 
        range: [10, 40, 1]